services:
  mongo:
    image: mongo:latest
    container_name: moviecollection-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - collection-network

networks:
  collection-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
